version: '3.5'

services: 
  app:
     container_name: potplayer-app
     image: 'pot-player-dictionary:latest'
     build:
       context: ./dockerfile
     depends_on:
       - postgres
     environment:
       - POSTGRESQL_URL=jdbc:postgresql://postgres:5432/dictionary
       - POSTGRESQL_USER=admin
       - POSTGRESQL_PASSWORD=admin
     restart: unless-stopped
     ports:
       - 8080:8081

  postgres:
     container_name: potplayer-postgres-server
     image: 'postgres:13.1-alpine'
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       PGDATA: /data/postgres
     volumes:
       - ./database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
     restart: unless-stopped
     ports:
       - 5432:5432   
  
  adminer:
     container_name: potplayer-adminer
     image: adminer
     restart: unless-stopped
     ports:
      - 9000:8080
